version: '3.8'

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./services/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=microservices
    depends_on:
      - db

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./services/web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://api:3000
    depends_on:
      - api

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=microservices
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: